# Site wide configuration
source                   : .tmp/src
destination              : .tmp/dist

title                    : "Odd One Out"
description              : "My blog about geeky projects"
logo                     : "/assets/images/todo.png"
teaser                   : "/assets/images/todo-default-teaser.png"
locale                   : "en_US"
words_per_minute         : 200

repository               : "psirek/Ox3-test"
url                      : "https://odd-one-out.serek.eu"

social:
  name                   : "Poul Serek"
  links:
    - "https://twitter.com/psirek"
    - "https://www.facebook.com/Odd-One-Out-Serekeu-850332811727698/"
    - "https://github.com/psirek"
    - "https://plus.google.com/u/0/+PoulSerek"

google_site_verification : "todo"
bing_site_verification   : "todo"
alexa_site_verification  : ""
yandex_site_verification : "todo"

google_ad-client         : ""
google_ad-slot           : ""
google_analytics         : "todo"

feed:
  path                  : "https://odd-one-out.serek.eu/atom.xml"

favicon_version         : "5A54z5oklP"

pingback_url            : "https://webmention.io/odd-one-out.serek.eu/xmlrpc"
webmention_url          : "https://webmention.io/odd-one-out.serek.eu/webmention"

# Site owner
author:
  name                   : "Poul Serek"
  uri                    : &uri "https://odd-one-out.serek.eu/about/"
  url                    : *uri
  bio                    : "Todo."
  picture                : "/assets/images/todo.jpg"
  twitter                : "https://twitter.com/psirek"
  facebook               : "https://www.facebook.com/Odd-One-Out-Serekeu-850332811727698/"
  instagram              : 
  tumblr                 : 
  github                 : "https://github.com/psirek"
  google_plus            : "https://plus.google.com/u/0/+PoulSerek"

twitter:
  username               : "psirek"

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch                 : "poc"

# reCAPTCHA keys
reCaptcha:
  siteKey: "6LchDDIUAAAAAG8oaPZ0uijNaFXHMcEpef0hbYHS"
  secret: "xU3bCzZxRFZ61ORS+A1vcAaE8LqsPt4QzjzqAWBOy68k8mL8+dkNJsPmAIkV5PQwkYVYXU4+FlkPlTbgG3Af5Snrs0l8cx70ASvvge4aGDdq8Rq3Z7GVs4/As9KaJEsQbdlyIubEXCflvl6ich7YoASUw/twx/iqx9Sj1wS8K40="

# Jekyll configuration
permalink                : /:categories/:title/
lsi                      : false
future                   : false
show_drafts              : false
markdown                 : kramdown
kramdown:
  toc_levels             : 1..3
  input                  : GFM
  hard_wrap              : false
  auto_ids               : true
  entity_output          : as_char
  smart_quotes           : lsquo,rsquo,ldquo,rdquo
  enable_coderay         : false
highlighter              : rouge
keep_files:
  - .git
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

# Plugins
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-typogrify

# Collections
collections:
#  work:
#    output    : true
#    permalink : /:collection/:path/
#    title     : Work
  components:
    output    : false
  colors:
    output    : false

# Front Matter Defaults
defaults:
  # Projects
  - scope:
      path: _posts/projects
      type: posts
    values:
      layout: post
      category: projects
      read_time: true
      comments: true
      support: true
      breadcrumbs:
        - label: "Projects"
          url: /projects/
  # Reviews
  - scope:
      path: _posts/reviews
      type: posts
    values:
      layout: post
      category: reviews
      read_time: true
      comments: true
      support: true
      breadcrumbs:
        - label: "Reviews"
          url: /reviews/
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled      : true
  debug        : false
  per_page     : 15
  permalink    : "/page/:num/"
  title        : ":title - Page :num of :max"
  limit        : 0
  sort_field   : "date"
  sort_reverse : true

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled      : true
  categories:
    enabled    : false
  collections:
    enabled    : false
  tags:
    enabled    : true
    layouts:
      - "autopage_tags.html"
    title      : ":tag" # :tag is replaced by the tag name
    permalink  : "/tag/:tag"
